jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NjM3MDYwMDd9.NpuB_nomYVXSNC0NGqLbAhaWWcsgnIxnNxojgoIZnSM

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "bob",
  "email": "bob@bob.com",
  "password": "password",
  "password_confirmation": "password"
}


### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "dan@dan.com",
  "password": "password"
}

#### STUDENT CREATE
POST http://localhost:3000/students.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjM3MDQxNjV9.JiLDCK3wwZM_z9Z-ow4AmaKU40q6QYOUcdEMD_yCu-A

### index students
GET http://localhost:3000/students.json

#### STUDENT SHOW

GET http://localhost:3000/students.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjM3ODgzNzd9.HZPfODI4QVh0KjQUudUnbBxwfKBGgM4a2Ve7xSXMRHE


### Student edit
PATCH http://localhost:3000/students/1.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjM2OTc5MTd9.gRyOmdhmO0E7g_N9QdCiu4KjKQazHVKU6qr3aEiXj0Y
Content-Type: application/json

{
  "twitter": "twitter.com/dantheman"
}

### Educations Create
DELETE http://localhost:3000/educations/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjM3MDIwNzR9.6Liy4cTu3bT4OYwW-kL0cUyNLzN5DmmpkaM1zfjpZM4
Content-Type: application/json

{
  "start_date": "1745-07-01",
  "end_date": "1212-12-01",
  "degree": "Bachelors",
  "university_name": "Jesuit university"
}

#######################################
### Experiences Create
POST http://localhost:3000/experiences
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjM3MDIwNzR9.6Liy4cTu3bT4OYwW-kL0cUyNLzN5DmmpkaM1zfjpZM4
Content-Type: application/json

{
  "start_date": "2022-07-01",
  "end_date": "2022-12-01",
  "job_title": "",
  "company_name": "Tesla",
  "details": ""

}

### EXPERIENCES index 
GET http://localhost:3000/experiences.json

#### EXPERIENCES SHOW

GET http://localhost:3000/experiences/1.json


### Experiences update 
PATCH http://localhost:3000/experiences/2.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjM3MDIwNzR9.6Liy4cTu3bT4OYwW-kL0cUyNLzN5DmmpkaM1zfjpZM4
Content-Type: application/json

{
  "start_date": "2020-07-01",
  "end_date": "2022-01-01"
  
}


#### EXPERIENCES DELETE

DELETE http://localhost:3000/experiences/1.json


#### CAPSTONE CREATE
POST http://localhost:3000/capstones
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjM3Nzk1MTl9.M6MLYwCuplslCwBI344guzZuySyUJ-O6gY452uzD978
Content-Type: application/json

{
  "name": "workout app",
  "description": "workout!!",
  "url": "www.workout.com",
  "screenshot": "workout.jpg"
}

### CAPSTONE EDIT
PATCH http://localhost:3000/capstones/2
Content-Type: application/json

{
  "name": "the best workout app"
}

### CAPSTONE DESTROY
DELETE http://localhost:3000/capstones/2

### CAPSTONE SHOW
GET http://localhost:3000/capstones/1


