### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "jim",
  "email": "jim@jim.com",
  "password": "password",
  "password_confirmation": "password"
}


### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "jim@jim.com",
  "password": "password"
}


#### STUDENT CREATE
POST http://localhost:3000/students
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NjM2OTU2OTR9.n0CMIHHBRZ4cyS8pnVjybOkegWID--79x5Onl2kS6Io

### index students
GET http://localhost:3000/students.json