### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Dan",
  "email": "dan@dan.com",
  "password": "password",
  "password_confirmation": "password"
}


### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "dan@dan.com",
  "password": "password"
}

#####
POST http://localhost:3000/students.json
Content-Type: application/json

{
  "first_name": "",
      "last_name": "",
      "email": "",
     "phone_number": "",
      "short_bio": "",
      "linked_in": "",
      "twitter": "",
      "blog_or_website": "",
      "online_resume": "",
      "github": "",
      "photo": "",
}